import { DataTable } from '@elektra/customComponents';
import { RootState } from '@elektra/store';
import { format } from 'date-fns';
import { useMemo } from 'react';
import { useSelector } from 'react-redux';
import { SalesHistory } from '../../../../../types/slices';

const tabledata = [
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
];
type SalesTableProps = {
  data:SalesHistory[]
}
export const SalesTable = ({data}:SalesTableProps) => {
  const salesTableData = useMemo(() => {
    return data?.map((item, key) => ({
      id: item?.id,
      itemName: item?.item_name ?? '-',
      condition: item?.condition,
      capacity: 'NID',
      carrier: 'NID',
      color: 'NID',
      lowestOffer: `$${item.lowest_offer}`,
      date: format(new Date(item.date), 'dd MMM, yyyy'),
    }));
  }, [data]);

  // return <>{salesTableData?.length > 0 && <DataTable data={salesTableData} />}</>;
  return <DataTable data={salesTableData} />;
};
