import { DataTable } from '@elektra/customComponents';
import { RootState } from '@elektra/store';
import { format } from 'date-fns';
import { useMemo } from 'react';
import { useSelector } from 'react-redux';

const tabledata = [
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
  {
    id: '1',
    itemName: 'Iphone Unlocked',
    condition: 'Used',
    capacity: '128GB',
    carrier: 'Jazz',
    color: 'Blue',
    lowestOffer: '$260',
    date: '20 Aug,2022',
  },
];
export const SalesTable = () => {
  const salesHistory = useSelector((state: RootState) => state.entities.productListingById.list.sales_history);
  const salesTableData = useMemo(() => {
    return salesHistory.map((item, key) => ({
      id: item.id,
      'Item Name': item.item_name,
      Condition: item.condition,
      Date: format(new Date(item.date), 'dd MMM, yyyy'),
      'Lowest Offer': item.lowest_offer,
    }));
  }, [salesHistory]);

  return <>{salesTableData.length > 0 && <DataTable data={salesTableData} />}</>;
};
