import { combineReducers } from '@reduxjs/toolkit';
import {
  brandReducer,
  couponReducer,
  feeReducer,
  genericCategoryReducer,
  notificationReducer,
  orderDetailReducer,
  payoutsReducer,
  productDataReducer,
  productLisingByIdReducer,
  productListingReducer,
  productVariantReducer,
  protectionPlanReducer,
  purchasingOrdersReducer,
  sellingOrdersReducer,
  specialProductReducer,
  userFavouriteReducer,
  userRewardReducer,
  websiteSectionReducer,
} from './slices';

export const entitiesReducers = combineReducers({
  websiteSection: websiteSectionReducer,
  protectionPlan: protectionPlanReducer,
  userReward: userRewardReducer,
  userFavourite: userFavouriteReducer,
  purchasingOrders: purchasingOrdersReducer,
  sellingOrders: sellingOrdersReducer,
  specialProducts: specialProductReducer,
  productDetail: productDataReducer,
  orderDetail: orderDetailReducer,
  productListing: productListingReducer,
  productVariants: productVariantReducer,
  productListingById: productLisingByIdReducer,
  coupon: couponReducer,
  fee: feeReducer,
  genericCategory: genericCategoryReducer,
  brand: brandReducer,
  notification: notificationReducer,
  payouts: payoutsReducer,
});
